#
# SDx module Makefile.
#
# Copyright (C) 2014-2015 North Atlantic Industries, Inc.
#

# SD is built from LD sources
MODULE_SRC = LD

# Include module specific Makefile
include $(MODULE_DIR)/$(MODULE_SRC)/Makefile

