#
# DSx module Makefile.
#
# Copyright (C) 2014-2015 North Atlantic Industries, Inc.
#

# Version numbers
FW_VER_MAJOR := 1
FW_VER_MINOR := 1

# Rev 1.0 - 10/13/2015 - Initial Release
# Rev 1.1 - 10/28/2015 - Added Fixed Mode, background calibration and made fix in output voltage scaling


# Additional module specific source files
MODULE_C += \
    #$(MODULE_DIR)/module_lib.c

# Additional module specific header files
MODULE_H += \
    #$(MODULE_DIR)/module_lib.h

