#
# DA1 module Makefile.
#
# Copyright (C) 2014-2015 North Atlantic Industries, Inc.
#

# Version numbers
FW_VER_MAJOR := 1
FW_VER_MINOR := 4

# Version 1.3 - 05/12/2015 - Now forcing span/range to update on power up 
# Version 1.4 - 06/16/2015 - Fixed BIT for voltage and current

# Additional module specific source files
MODULE_C += \
    #$(MODULE_DIR)/module_lib.c

# Additional module specific header files
MODULE_H += \
    #$(MODULE_DIR)/module_lib.h

