#
# DA3 module Makefile.
#
# Copyright (C) 2014-2015 North Atlantic Industries, Inc.
#

# Version numbers
FW_VER_MAJOR := 1
FW_VER_MINOR := 0

# Additional module specific source files
MODULE_C += \
    #$(MODULE_DIR)/module_lib.c

# Additional module specific header files
MODULE_H += \
    #$(MODULE_DIR)/module_lib.h

